CREATE DATABASE IF NOT EXISTS simple_notebooks CHARACTER SET utf8 collate utf8_general_ci;
CREATE USER IF NOT EXISTS 'gingin'@'localhost' IDENTIFIED BY 'Pass2438';
GRANT ALL ON simple_notebooks.* TO 'gingin'@'localhost';

CREATE TABLE IF NOT EXISTS users ( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_name VARCHAR(50), password VARCHAR(128));
CREATE TABLE IF NOT EXISTS notebooks ( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, subject VARCHAR(100), text VARCHAR(500), is_private BOOLEAN);
CREATE TABLE IF NOT EXISTS faves ( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, note_id INT NOT NULL DEFAULT '0', user_id INT NOT NULL DEFAULT '0');
